name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach git head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "push changes back to github"
        run:  |
          . <(java -jar ~/buildtools.jar)
          # pushBackToGithub

      - name: "check num commits"
        run:  |
          git rev-list --all --count
